package me.puneetghodasara.txmgr.core.exception;

public enum ExceptionKey {
	DB_EXCEPTION, INVALID_PARAM, DUPLICATE_ACCOUNT_NAME, NO_FOLDER_AVBL, RULE_FILE_NOT_FOUND, CREDIT_DEBIT_PARSE_ERROR, FILE_ALREADY_UPLOADED

}
